services:
  soap-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAVA_OPTS=-Xmx512m -Xms256m
    ports:
      - "8080:8080"
    container_name: soap-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/data-service?wsdl"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M
networks:
  backend-network:
    driver: bridge