services:
  frontend_app:
    container_name: integration_frontend
    build:
      context: ./IntegracjaFrontend/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontend_network
    depends_on:
      - frontend_backend
    restart: unless-stopped

  frontend_backend:
    container_name: integration_backend
    build:
      context: ./IntegracjaFrontend/backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${DB_HOST:-frontend_mongodb}
      - DB_PORT=${DB_PORT:-27017}
      - NODE_ENV
      - SOAP_URL
    secrets:
      - jwt_secret
      - db_user
      - db_password
      - db_name
    networks:
      - frontend_network
      - user_network
      - soap_network
    depends_on:
      frontend_mongodb:
        condition: service_healthy
      soap-service:
        condition: service_healthy
    restart: unless-stopped

  frontend_mongodb:
    container_name: ${DB_HOST:-frontend_mongodb}
    image: mongo:latest
    command: mongod --port ${DB_PORT:-27017}
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MONGO_INITDB_DATABASE_FILE: /run/secrets/db_name
    secrets:
      - db_user
      - db_password
      - db_name
    volumes:
      - frontend-mongodb-data:/data/db
    networks:
      - user_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok || exit(1)"]
      interval: 30s
      timeout: 10s
      retries: 2

  soap-service:
    build:
      context: ./IntegracjaBackend
      dockerfile: Dockerfile
      args:
        - JAVA_OPTS=-Xmx512m -Xms256m
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    container_name: soap-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/data-service?wsdl"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - soap_network
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M
    secrets:
      - jwt_secret

networks:
  frontend_network:
    driver: bridge
  user_network:
    driver: bridge
  soap_network:
    driver: bridge

volumes:
  frontend-mongodb-data:

secrets:
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  db_name:
    file: ./secrets/db_name.txt 