services:
  frontend_controller:
    ports:
      - "3001:3001"
  
  users_db:
    ports:
      - "${DB_PORT:-27017}:${DB_PORT:-27017}"
  
  soap-service:
    ports:
      - "8080:8080"

  mysql-jpa:
    ports:
      - "3306:3306"

  api-interactor:
    ports:
      - "8090:8090"
