services:
  backend:
    container_name: integration_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgrespassword}
      - DB_NAME=${DB_NAME:-integration_db}
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_here}
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3001:3001"
    networks:
      - integration-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    container_name: integration_db
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgrespassword}
      POSTGRES_DB: ${DB_NAME:-integration_db}
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - integration-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: integration_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - integration-network
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  integration-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data: 